name = "Random Improvements"
uid = "64b07567-334e-4206-8ba9-98c89da0aecf"
version = 1
copyright = ""
description = "Displays rings of common ranges with numpad 1-9, clear with numpad '.'. Toggle selected unit ranges with numpad0."
author = "Hellomouse"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
